# Generated by Django 6.1 on 2026-08-20 13:09

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("identity", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdempotencyKey",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "user_id",
                        "key",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.UUIDField()),
                ("endpoint", models.TextField()),
                ("request_body_hash", models.TextField()),
                (
                    "status",
                    models.TextField(
                        choices=[("in_progress", "In progress"), ("completed", "Completed")]
                    ),
                ),
                ("response_status", models.IntegerField(blank=True, null=True)),
                (
                    "response_body",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="identity.appuser",
                    ),
                ),
            ],
            options={
                "db_table": "idempotency_key",
                "indexes": [models.Index(fields=["created_at"], name="idx_idempotency_created")],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["in_progress", "completed"])),
                        name="idempotency_key_status_check",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("completed_at__isnull", False),
                                ("response_status__isnull", False),
                                ("status", "completed"),
                            ),
                            models.Q(("response_status__isnull", True), ("status", "in_progress")),
                            _connector="OR",
                        ),
                        name="completed_has_response",
                    ),
                ],
            },
        ),
    ]
