# Generated by Django 6.1 on 2026-08-20 22:28

import uuid

import django.core.serializers.json
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_kairos_app_recurring_series_grants"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemCheckRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "check_name",
                    models.TextField(
                        choices=[
                            ("reconciliation", "Reconciliation"),
                            ("schema_assertion", "Schema assertion"),
                            ("hold_reaper", "Hold reaper"),
                            ("offer_cascade", "Offer cascade"),
                            ("series_materialization", "Series materialization"),
                            ("tzdata_rematerialization", "Tzdata re-materialization"),
                        ]
                    ),
                ),
                (
                    "run_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("status", models.TextField(choices=[("pass", "Pass"), ("fail", "Fail")])),
                (
                    "findings",
                    models.JSONField(
                        default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder
                    ),
                ),
            ],
            options={
                "db_table": "system_check_run",
                "indexes": [
                    models.Index(fields=["check_name", "-run_at"], name="idx_check_run_latest")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "check_name__in",
                                [
                                    "reconciliation",
                                    "schema_assertion",
                                    "hold_reaper",
                                    "offer_cascade",
                                    "series_materialization",
                                    "tzdata_rematerialization",
                                ],
                            )
                        ),
                        name="system_check_run_check_name_check",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["pass", "fail"])),
                        name="system_check_run_status_check",
                    ),
                ],
            },
        ),
    ]
