# Generated by Django 6.1 on 2026-08-21 09:48

import uuid

import django.core.serializers.json
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_kairos_app_waitlist_offer_grants_and_trigger"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "notification_type",
                    models.TextField(
                        choices=[
                            ("offer_created", "Offer created"),
                            ("admin_cancellation", "Admin cancellation"),
                            ("tzdata_rematerialization", "Tzdata re-materialization"),
                            (
                                "tzdata_rematerialization_conflict",
                                "Tzdata re-materialization conflict",
                            ),
                            ("rollback_hold_released", "Rollback hold released"),
                        ]
                    ),
                ),
                ("recipient_user_id", models.UUIDField()),
                ("recipient_email", models.TextField()),
                ("subject", models.TextField()),
                ("body", models.TextField()),
                (
                    "context",
                    models.JSONField(
                        default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[("pending", "Pending"), ("sent", "Sent"), ("failed", "Failed")],
                        default="pending",
                    ),
                ),
                ("attempts", models.IntegerField(default=0)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("request_id", models.TextField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "notification_log",
                "indexes": [
                    models.Index(
                        fields=["recipient_user_id", "-created_at"],
                        name="idx_notification_recipient",
                    ),
                    models.Index(
                        fields=["notification_type", "-created_at"], name="idx_notification_type"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "notification_type__in",
                                [
                                    "offer_created",
                                    "admin_cancellation",
                                    "tzdata_rematerialization",
                                    "tzdata_rematerialization_conflict",
                                    "rollback_hold_released",
                                ],
                            )
                        ),
                        name="notification_log_type_check",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["pending", "sent", "failed"])),
                        name="notification_log_status_check",
                    ),
                ],
            },
        ),
    ]
