# Generated by Django 6.1 on 2026-08-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_kairos_app_notification_log_grants"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="notificationlog",
            name="notification_log_type_check",
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="notification_type",
            field=models.TextField(
                choices=[
                    ("offer_created", "Offer created"),
                    ("admin_cancellation", "Admin cancellation"),
                    ("tzdata_rematerialization", "Tzdata re-materialization"),
                    ("tzdata_rematerialization_conflict", "Tzdata re-materialization conflict"),
                    ("rollback_hold_released", "Rollback hold released"),
                    ("series_owner_deactivated", "Series owner deactivated"),
                ]
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationlog",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "notification_type__in",
                        [
                            "offer_created",
                            "admin_cancellation",
                            "tzdata_rematerialization",
                            "tzdata_rematerialization_conflict",
                            "rollback_hold_released",
                            "series_owner_deactivated",
                        ],
                    )
                ),
                name="notification_log_type_check",
            ),
        ),
    ]
