# Generated by Django 6.1 on 2026-08-20 11:04

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.TextField()),
                ("category", models.TextField(default="meeting_room")),
                ("timezone", models.TextField()),
                ("bookable_start_time", models.TimeField()),
                ("bookable_end_time", models.TimeField()),
                ("max_booking_duration_minutes", models.IntegerField(blank=True, null=True)),
                (
                    "offboarding_policy",
                    models.TextField(
                        choices=[
                            ("transfer", "Transfer"),
                            ("cancel_and_notify", "Cancel and notify"),
                            ("retain", "Retain"),
                        ],
                        default="transfer",
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[("active", "Active"), ("inactive", "Inactive")], default="active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="identity.appuser",
                    ),
                ),
            ],
            options={
                "db_table": "resource",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("offboarding_policy__in", ["transfer", "cancel_and_notify", "retain"])
                        ),
                        name="resource_offboarding_policy_check",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["active", "inactive"])),
                        name="resource_status_check",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("bookable_end_time__gt", models.F("bookable_start_time"))
                        ),
                        name="bookable_window_valid",
                    ),
                ],
            },
        ),
    ]
