# Generated by Django 6.1 on 2026-08-20 11:04

import uuid

import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("identity", "0002_initial"),
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("time_range", django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                (
                    "starts_at",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Func(
                            "time_range", function="lower", output_field=models.DateTimeField()
                        ),
                        output_field=models.DateTimeField(),
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("confirmed", "Confirmed"),
                            ("held", "Held"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="confirmed",
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True, null=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="cancelled_by",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="cancelled_bookings",
                        to="identity.appuser",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        db_column="resource_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="resources.resource",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="bookings",
                        to="identity.appuser",
                    ),
                ),
            ],
            options={
                "db_table": "booking",
                "indexes": [
                    models.Index(
                        condition=models.Q(("status", "held")),
                        fields=["expires_at"],
                        name="idx_booking_hold_expiry",
                    ),
                    models.Index(
                        fields=["user", "starts_at", "id"], name="idx_booking_user_starts"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["confirmed", "held", "cancelled"])),
                        name="booking_status_check",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("time_range__isempty", False)),
                        name="booking_time_range_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("expires_at__isnull", False), ("status", "held")),
                            models.Q(
                                models.Q(("status", "held"), _negated=True),
                                ("expires_at__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="hold_has_expiry",
                    ),
                ],
            },
        ),
    ]
