# Generated by Django 6.1 on 2026-08-20 20:30

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0002_exclusion_constraint"),
        ("identity", "0004_usergroup_usergroupmembership"),
        ("resources", "0002_resource_restricted_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringSeries",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("timezone", models.TextField()),
                ("local_start_time", models.TimeField()),
                ("local_end_time", models.TimeField()),
                ("weekday", models.SmallIntegerField()),
                ("series_start_date", models.DateField()),
                ("occurrence_count", models.SmallIntegerField()),
                ("tzdata_version", models.TextField()),
                ("materialized_through", models.DateField()),
                (
                    "status",
                    models.TextField(
                        choices=[("active", "Active"), ("cancelled", "Cancelled")], default="active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="identity.appuser",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        db_column="resource_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="resources.resource",
                    ),
                ),
            ],
            options={
                "db_table": "recurring_series",
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="series",
            field=models.ForeignKey(
                blank=True,
                db_column="series_id",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="bookings",
                to="bookings.recurringseries",
            ),
        ),
        migrations.AddIndex(
            model_name="recurringseries",
            index=models.Index(
                condition=models.Q(("status", "active")),
                fields=["tzdata_version", "timezone"],
                name="idx_series_tzdata",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringseries",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "cancelled"])),
                name="recurring_series_status_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringseries",
            constraint=models.CheckConstraint(
                condition=models.Q(("weekday__gte", 0), ("weekday__lte", 6)),
                name="recurring_series_weekday_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringseries",
            constraint=models.CheckConstraint(
                condition=models.Q(("occurrence_count__gte", 1), ("occurrence_count__lte", 100)),
                name="recurring_series_occurrence_count_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringseries",
            constraint=models.CheckConstraint(
                condition=models.Q(("local_end_time__gt", models.F("local_start_time"))),
                name="series_window_valid",
            ),
        ),
    ]
