# Generated by Django 6.1 on 2026-08-20 11:04

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("email", models.TextField(unique=True)),
                ("display_name", models.TextField()),
                (
                    "platform_role",
                    models.TextField(
                        choices=[
                            ("booker", "Booker"),
                            ("system_admin", "System Administrator"),
                            ("operations", "Operations"),
                        ],
                        default="booker",
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[("active", "Active"), ("deactivated", "Deactivated")],
                        default="active",
                    ),
                ),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "app_user",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("platform_role__in", ["booker", "system_admin", "operations"])
                        ),
                        name="app_user_platform_role_check",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["active", "deactivated"])),
                        name="app_user_status_check",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("deactivated_at__isnull", False), ("status", "deactivated")),
                            models.Q(("deactivated_at__isnull", True), ("status", "active")),
                            _connector="OR",
                        ),
                        name="deactivated_has_timestamp",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ResourceAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        db_column="granted_by",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="granted_admin_scopes",
                        to="identity.appuser",
                    ),
                ),
            ],
            options={
                "db_table": "resource_admin",
            },
        ),
    ]
