# Generated by Django 6.1 on 2026-08-20 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("identity", "0001_initial"),
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourceadmin",
            name="resource",
            field=models.ForeignKey(
                db_column="resource_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin_grants",
                to="resources.resource",
            ),
        ),
        migrations.AddField(
            model_name="resourceadmin",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin_grants",
                to="identity.appuser",
            ),
        ),
        migrations.AddConstraint(
            model_name="resourceadmin",
            constraint=models.UniqueConstraint(
                fields=("resource", "user"), name="resource_admin_unique_grant"
            ),
        ),
    ]
