"""ResourceAdmin's surrogate `id` was an implicit BigAutoField (Django's
DEFAULT_AUTO_FIELD, since Phase 2 never declared `id` explicitly on this
model) — inconsistent with every other entity table in this schema
(app_user/resource/booking all declare an explicit UUIDField PK). Phase 8's
`write_audit_log()` trigger does `COALESCE(NEW.id, OLD.id)` into
`audit_log.entity_id UUID`, and a bigint surrogate key fails that INSERT
with a type mismatch — caught empirically the first time a test wrote a
`ResourceAdmin` row after the audit trigger was attached to this table.

`resource_admin` carries no production data at this point in the project
(Phase 19, the first phase that writes to it via a real endpoint, hasn't
landed yet), so this is a straightforward ALTER, not a backfill — RunSQL,
not Django's auto-generated `AlterField` SQL, because Django's generic
`ALTER COLUMN "id" TYPE uuid USING "id"::uuid` assumes a cast exists
between the old and new types. Postgres has no bigint->uuid cast at all
(confirmed empirically: `cannot cast type bigint to uuid`), so the column
has to be dropped and re-added rather than converted in place. This is
only safe BECAUSE the table is empty; `state_operations` keeps Django's
migration state in sync with what `AlterField` would have produced, so
`makemigrations --check` still reports no drift afterward.
"""

import uuid

from django.db import migrations, models

FORWARD_SQL = """
ALTER TABLE resource_admin DROP CONSTRAINT resource_admin_pkey;
ALTER TABLE resource_admin DROP COLUMN id;
ALTER TABLE resource_admin ADD COLUMN id UUID NOT NULL DEFAULT gen_random_uuid();
ALTER TABLE resource_admin ADD PRIMARY KEY (id);
DROP SEQUENCE IF EXISTS resource_admin_id_seq;
"""

REVERSE_SQL = """
ALTER TABLE resource_admin DROP CONSTRAINT resource_admin_pkey;
ALTER TABLE resource_admin DROP COLUMN id;
ALTER TABLE resource_admin ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE resource_admin ADD PRIMARY KEY (id);
"""


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0002_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql=FORWARD_SQL,
            reverse_sql=REVERSE_SQL,
            state_operations=[
                migrations.AlterField(
                    model_name="resourceadmin",
                    name="id",
                    field=models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
            ],
        ),
    ]
