# Generated by Django 6.1 on 2026-08-21 07:05

import uuid

import django.contrib.postgres.fields.ranges
import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("identity", "0004_usergroup_usergroupmembership"),
        ("resources", "0002_resource_restricted_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaitlistEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("time_range", django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("offered", "Offered"),
                            ("fulfilled", "Fulfilled"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="waiting",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        db_column="resource_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="waitlist_entries",
                        to="resources.resource",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="waitlist_entries",
                        to="identity.appuser",
                    ),
                ),
            ],
            options={
                "db_table": "waitlist_entry",
                "indexes": [
                    django.contrib.postgres.indexes.GistIndex(
                        condition=models.Q(("status", "waiting")),
                        fields=["resource", "time_range"],
                        name="idx_waitlist_entry_lookup",
                    ),
                    models.Index(
                        condition=models.Q(("status", "waiting")),
                        fields=["resource", "joined_at", "id"],
                        name="idx_waitlist_entry_order",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                ["waiting", "offered", "fulfilled", "expired", "cancelled"],
                            )
                        ),
                        name="waitlist_entry_status_check",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("time_range__isempty", False)),
                        name="wl_entry_time_range_not_empty",
                    ),
                ],
            },
        ),
    ]
