# Generated by Django 6.1 on 2026-08-21 08:14
#
# ============================================================
# NO EXCLUDE CONSTRAINT ON THIS TABLE. Reproduced verbatim from Spec v1.0
# §3 (Implementation Plan Phase 16 Scope — the "forbidding comment" this
# migration must carry):
#
# v0.1 of this spec carried an EXCLUDE constraint on this table to prevent
# two workers offering the same freed slot. That constraint is GONE and
# must not be restored. It solved offer-vs-offer collisions only, while
# leaving offer-vs-booking collisions entirely unprotected — because two
# constraints on two different tables cannot exclude against each other
# (RFC v1.0 §15c). Mutual exclusion now lives in ONE place: the hold row
# in `booking`. A second concurrent offer would require a second
# overlapping hold, which `no_overlapping_bookings` already forbids
# (PRD FR25).
#
# If you are reading this while considering adding an EXCLUDE constraint
# back to `waitlist_offer`: STOP. It would not restore any guarantee this
# table is missing — the guarantee already lives on `booking` — and it
# would resurrect the exact split-brain mutual-exclusion bug (RFC v1.0
# §15c) this redesign exists to eliminate.
# ============================================================

import uuid

import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0004_series_materialized_through_index"),
        ("resources", "0002_resource_restricted_group"),
        ("waitlist", "0002_uniq_live_waitlist_per_user_slot"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaitlistOffer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("time_range", django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("active", "Active"),
                            ("confirmed", "Confirmed"),
                            ("expired", "Expired"),
                            ("declined", "Declined"),
                        ],
                        default="active",
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                (
                    "hold_booking",
                    models.OneToOneField(
                        db_column="hold_booking_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="waitlist_offer",
                        to="bookings.booking",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        db_column="resource_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="waitlist_offers",
                        to="resources.resource",
                    ),
                ),
                (
                    "waitlist_entry",
                    models.ForeignKey(
                        db_column="waitlist_entry_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="offers",
                        to="waitlist.waitlistentry",
                    ),
                ),
            ],
            options={
                "db_table": "waitlist_offer",
                "indexes": [
                    models.Index(
                        condition=models.Q(("status", "active")),
                        fields=["expires_at"],
                        name="idx_waitlist_offer_expiry",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status__in", ["active", "confirmed", "expired", "declined"])
                        ),
                        name="waitlist_offer_status_check",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("time_range__isempty", False)),
                        name="wo_time_range_not_empty",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "active")),
                        fields=("waitlist_entry",),
                        name="uniq_active_offer_per_entry",
                    ),
                ],
            },
        ),
    ]
